apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  labels:
    app: ollama
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/ollama-data
    type: DirectoryOrCreate