apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
        - name: http
          containerPort: 11434
          protocol: TCP
      volumeMounts:
        - name: ollama-data
          mountPath: /data
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c"]
            args:
             - ollama pull llama3.2 && \
             - ollama pull nomic-embed-text && \
             - ollama serve
    volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    name: ollama
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP